### ISSUE TITLE
Windows tools in bin still missing

### ISSUE THREAD

**Issue by Fpadt** [OpenVPN/easy-rsa#110]
Hi eric,

when i download the 3.0.1 the bin folder only contains a .sh file. No *.exe, e.g. sh.exe, which.exe
I will take them from an older version

just wanted to let you know

**Comment by kekwowse01** [comment]
The v3.0.0-rc2 has multiple .exe files. Should I copy all of them for v3.0.1?

**Comment by ToddAndMargo** [comment]
Is windows no longer supported?

**Comment by gsloop** [comment]
So, download 3.0.0-rc2, and use the exe files from the /bin directory with the rest of the release from 3.0.1.

That fixes most things, but there's another issue [non POSIX code] which needs mktemp, which isn't in any release.

So, while it would be best to fix the non POSIX code in the release, this will fix the mktemp issue.
Download: gnuwin32.sourceforge.net/packages/mktemp.htm - grab the zip file and extract the mktemp.exe to the same /bin directory.

Now the init-ca command will work.
[I haven't yet generated a full set of certs/keys, so I'm not sure the above fixes will fix every problem, but hopefully it will.]

**Comment by Fpadt** [comment]
thanks, Seems to work

**Comment by gsloop** [comment]
Please don't close the issue. It's very much still NOT fixed - though what I offer is a work-around. [Cludgy at best.] This missing utility needs to be fixed in EastRSA - not some hack of copying files from somewhere else [that might go away, or the links break etc.] and merging the two.

So, yeah - please don't close the issue.

**Comment by TinCanTech** [comment]
@ gsloop .. Agree
