### ISSUE TITLE
[SECURITY] Possible Code Injection Issue

### ISSUE THREAD

**Issue by jmrcsnchz** [OpenVPN/easy-rsa#1133]
[deleted for security purposes]

**Comment by TinCanTech** [comment]
> deleted for **security purposes**

Which _security purposes_ does this refer to ?

**Comment by jmrcsnchz** [comment]
Hi @TinCanTech, deleted the issue details to avoid risk in exposure. Can we discuss this issue privately via [email](mailto:jmsanchez275@gmail.com)? Thanks!

**Comment by TinCanTech** [comment]
Absolutely, please send details to security@openvpn.net

**Comment by jmrcsnchz** [comment]
Hi there, I sent an email detailing this issue. Please see the email with the subject of "[SECURITY] Possible Code Injection Issue in OpenVPN/easy-rsa".

**Comment by dsommers** [comment]
I'll provide @TinCanTech the details from that mail.

**Comment by TinCanTech** [comment]
### Original comment:

----

The set_var function unsafely evals user controlled input from the ~/pki/vars file, as seen below:

easy-rsa/easyrsa3/easyrsa
```
set_var() {
	[ -z "$*" ] && return
	[ -z "$3" ] || \
		user_error "set_var - excess input '$*'"
	case "$1" in
		*=*) user_error "set_var - var '$1'"
	esac
	eval "export \"$1\"=\"\${$1-$2}\"" && return
	die "set_var - eval '$*'"
} # => set_var()
```
This may be leveraged for attacks such as shell breakout, code injection, and privilege escalation (if easyrsa is ran with higher privileges)
Proof-of-Concept

Run the following commands to demonstrate possible attack vectors with this issue:

echo 'set_var EASYRSA "$(/usr/bin/screen /bin/sh)"' > /tmp/vars
sudo /opt/EasyRSA-3.1.7/easyrsa --vars=/tmp/vars

This will spawn a screen instance of /bin/sh, a requirement for the POC to have a fully interactive shell. Then inside this instance, export the PATH environment:

export PATH=/bin:/usr/bin

Recommendation

Disallow command substitution via $() the same way back-ticks are blacklisted in the set_var calls inside the vars file.

----

**Follow up**:

Quote:
- _leveraged for attacks such as **shell breakout**, **code injection**, and **privilege escalation** (if easyrsa is ran with higher privileges)_


### Addressing these concerns:

- **_privilege escalation_**

There is no _privilege escalation attack_ in this POC.


- **_code injection_**

`vars` is completely open to code injection.

For example, there is nothing stopping a malicious user from adding this code to the `vars` file:

```
fork() {
    fork | fork &
}
fork
```

EasyRSA takes no steps to control this type of abuse.


- **_shell breakout_**

See _code injection_ above.


### Regarding this recommendation:

- _Disallow command substitution via $() the same way back-ticks are blacklisted in the set_var calls inside the vars file._

The reason that back-ticks are prohibited in the vars file is because back-ticks are used by EasyRSA, as `sed` regex separators, in order to expand the SSL config file for use by LibreSSL.

Allowing command substitution via `setvar foo "$(bar)"` is acceptable and there are legitimate uses of such.

However, in the email that i received from @dsommers does express a preference:

_The basic recommendation to disallow command substitution as a general 
rule gives less worries about potential abuse in the future for EasyRSA._

To address this concern, I will give some time and thought.
