### ISSUE TITLE
easyrsa in $PATH, sign-req cannot find x509-types

### ISSUE THREAD

**Issue by PAStheLoD** [OpenVPN/easy-rsa#131]
Hello,

I'm using the current master (5a429d22), downloaded it and put the whole easyrsa3 directory under /usr/local, and symlinked easyrsa as /usr/local/bin/easyrsa.

It works pretty well, except I had to make 2 small modifications:

```
set_var EASYRSA "$(dirname $(readlink -f $0))"  # line 1016
...
set_var EASYRSA_PKI "$PWD/pki"
```

Is this a supported mode of operation at all?

**Comment by oreinert** [comment]
You happened to do your testing shortly before PR #128 was merged. That change fixes this issue, at least partially. Would you mind testing again with the current master (243f729)?

**Comment by SpareSimian** [comment]
How should $EASY_PKI/x509-types get populated? As a packager, I'd like to put the distro copy under /usr/lib/easy-rsa and check there for the default if it's not available under the user's pki directory.

It looks like I could define EASYRSA_EXT_DIR=/usr/lib/easy-rsa/x509-types in /etc/profile.d/easy-rsa.{sh,csh}.

**Comment by oreinert** [comment]
Ultimately, if nothing more specific is configured, the `EASYRSA` variable is used to locate the default configuration (roughly speaking, at least). This applies to vars, openssl-1.0.cnf and x509-types. The default location is where the `easyrsa` script is, corresponding to your local clone of the git repository. To specify some other default location (e.g., because your package puts the configuration somewhere else) I think the most sensible approach is to patch the `easyrsa` script.

For example, the openSUSE package of _easy-rsa_ (which I maintain) puts the default configuration files in `/etc/easy-rsa`, and the `easyrsa` script is patched accordingly - see https://build.opensuse.org/package/view_file/network:vpn/easy-rsa/suse-packaging.patch.

**Comment by SpareSimian** [comment]
That looks reasonable, but it does seem to encourage running it as root. I may patch to look in /usr/share/easy-rsa. The vars file should be copied from vars.example and edited after an init-pki. I'd package that file to /usr/share/doc/easy-rsa-3.0.3 to follow the example of other packages. With that done any user can have their own private pki directory.

**Comment by oreinert** [comment]
I guess you are aware that there is nothing about managing a PKI that inherently requires root access. But sometimes packages are put together in such a way that it becomes a necessity. In my opinion, it's a bug if that is the case.

My earlier comment presumed that `/etc/easy-rsa` is world-readable, which is the case in the openSUSE package. Thus, because of the patch, any user, including root, will use those files as the default configuration when running the `easyrsa` command. Also, any user can customize the configuration of a private PKI by copying the relevant default configuration file(s) to the private pki directory and modifying them as needed.

In my opinion, patching `easyrsa` to look for default configuration under `/usr/share` is a bit weird. That location is typically used for shared resources, documentation, and examples. Putting _vars.example_ there would be fine - but, on the other hand, it is not unusual for packages to place configuration template files in `/etc` for convenience, so that's what I chose.

**Comment by SpareSimian** [comment]
I've seen it both ways in the Red Hat world. Some put defaults in /etc but it seems that newer packages put it in /usr/share and /etc is a copy with overrides so that it's not clobbered by upgrades and has just the minimal changes the user needs for host-wide defaults. /usr/share would be for original factory-installed configuration and /usr/share/doc would be for example configuration (like var.example). Compare the layouts of systemd and fail2ban, for example.

**Comment by oreinert** [comment]
Interesting - I can definitely see the argument for keeping pristine configuration somewhere separate. On more than one occasion I have wished such a copy existed, to easily figure out what I have changed.

**Comment by TinCanTech** [comment]
Linking #499

**Comment by TinCanTech** [comment]
Any further feedback with current code ?
