### ISSUE TITLE
subjectAltName support

### ISSUE THREAD

**Issue by ghost** [OpenVPN/easy-rsa#22]
Found an old patch for easy-rsa 2 at http://www.msquared.id.au/articles/easy-rsa-subjectaltname/

Is there any plan to add this feature in easy-rsa 3?

**Comment by gsauthof** [comment]
@QueuingKoala FWIW, your example usage doesn't work with easy-rsa 3.0.3. The `--subject-alt-name` option doesn't have an effect with the `gen-req` command.

This does work:

    easyrsa init-pki
    easyrsa --batch build-ca nopass
    easyrsa --batch --req-cn=example.org gen-req example.org nopass
    easyrsa --batch --subject-alt-name='DNS:example.org,DNS:www.example.org'  \
        sign-req server example.org

**Comment by nemethloci** [comment]
Seems to work fine with latest version:

`$ ./easyrsa --subject-alt-name="DNS:www.example.net,DNS:secure.example.net" build-server-full 
alttest nopass`
...
...
...


`$ openssl x509 -in pki/issued/alttest.crt -text|grep -A1 'Alternative'
            X509v3 Subject Alternative Name: 
                DNS:www.example.net, DNS:secure.example.net`

$ git branch
 v3.0.5

**Comment by jpawlowski** [comment]
Currently SAN can only be added when signing the request with sign-req. If you put the SAN into the reqeust file for separate signature using gen-req, it won’t be part of the certificate as v3 extensions are not being copied per default.

Using build-server-full just looks different because it adds the SAN info to the sign-req command, not gen-req command.

There is copy_extensions for openssl.cnf but it won’t work at the moment. Also, taking over every v3 ext might be a risk. I understood this is why copy_extensions is not enabled by default but should be added individuuwhen required. That being said, the current parameter implementation —copy-ext does not work in easy-rsa 3.0.5.
There is a separate issue reported here.

**Comment by awienecke** [comment]
Not sure why this issue was closed, this still has issues with SAN, it will not assign them in any manner that is functional to other clients.

**Comment by ecrist** [comment]
The person that opened it closed it themselves. 

Eric Crist

**Comment by awienecke** [comment]
Not to be a bug, but if there was a way I could modify it so all batch csr's get the DNS SAN entry that matches the CN, I'd be a happy camper... I'm just not sure where exactly it's failing and what I would need to manually pass (and where) to makes sure that it gets the variables I want.

**Comment by nimbius** [comment]
hey,
this probably needs some formal documentation or an update to the easyrsa docs in general.  @nemethloci has a working solution for this, but nowhere in --help is it documented.  no real work necessary, just make sure people know how its done?
