### ISSUE TITLE
Zip/Tgz packages naming convention

### ISSUE THREAD

**Issue by zjagust** [OpenVPN/easy-rsa#391]
Hello,

This is more maybe a "feature request" than issue, but still here it goes. 

I'm trying to write a script that will download and install the latest version of EasyRSA on my Linux machine. I managed to write a "check" that will determine the latest version of your zip/tgz EasyRSA package based on version number, when I encountered the following problem; almost every release has a different file name of the zip/tgz package. For instance:

Version 3.0.7 -> EasyRSA-3.0.7.tgz
Version 3.0.6 -> EasyRSA-unix-v3.0.6.tgz
Version 3.0.5 -> EasyRSA-nix-3.0.5.tgz
Version 3.0.4 -> EasyRSA-3.0.4.tgz

Can you please decide on some sort of "standard" naming scheme for your zip/tgz packages. It would help alot. Thank you in advance.

BR,
Zeljko Jagust

**Comment by ecrist** [comment]
Hah, yeah, that's kinda lame of me.  I'll stick to the EasyRSA-M.m.r.tgz format in the future.  The windows releases will be similar, with Win added (EasyRSA-Win-M.m.r.zip).

Apologies for the oversight on my part. I'm marking this "closed" since there isn't a to-do really short of my naming the files on release.

**Comment by zjagust** [comment]
Much appreciated!
