### ISSUE TITLE
default_crl_days config setting ignored due to config-file syntax

### ISSUE THREAD

**Issue by juerg-myosh** [OpenVPN/easy-rsa#431]
The "default_crl_days" setting (for the gen-crl command) is ignored by OpenSSL because of the configuration file (openssl-easyrsa.cnf) syntax of that line. It requires a space (or tab?) after "default_crl_days" . The line should be:

`default_crl_days = $ENV::EASYRSA_CRL_DAYS	# how long before next CRL`

Currently, the line reads "default_crl_days= $ENV::EASYRSA_CRL_DAYS".

As a result, any EASYRSA_CRL_DAYS settings are not taking effect.

This has been observed with Easy-RSA v3.0.8 and OpenSSL v1.0.2k-fips (Amazon Linux 2).

Cheers

**Comment by dariosusman** [comment]
Even after changing that, which you're correct, it won't sort it out.  The problem is how easyrsa detects itself running from.

On debian, if you're running it as a symlink, the working directory will be /usr/share/easy-rsa, instead of whatever path you're running it from. And it doesn't find the vars file in there. So, in order to avoid throwing an error, it generates a configuration file of its own instead.
```# bash -x ./easyrsa  gen-crl
+ NL='
'
+ '[' -z '' ']'
+ umask 077
+ :
+ opt=gen-crl
+ val=gen-crl
+ empty_ok=
+ case "$opt" in
+ break
+ vars_setup
+ vars=
+ prog_file=./easyrsa
++ which -- ./easyrsa
+ prog_file2=./easyrsa
+ prog_file=./easyrsa
++ readlink -f ./easyrsa
+ prog_file2=/usr/share/easy-rsa/easyrsa
+ prog_file=/usr/share/easy-rsa/easyrsa
+ prog_dir=/usr/share/easy-rsa
+ prog_vars=/usr/share/easy-rsa/vars
+ pki_vars=/etc/openvpn/ca/pki/vars
+ '[' '!' -z '' ']'
+ '[' -f /etc/openvpn/ca/pki/vars ']'
+ '[' -n '' ']'
+ '[' -f /usr/share/easy-rsa/vars ']'
+ '[' -z '' ']'
+ '[' -n '' ']'
+ set_var EASYRSA /usr/share/easy-rsa
+ var=EASYRSA
</SNIP>
```

The only way I've found to solve this is is to force the path to the vars file manually like this:

```root@warpcore:/etc/openvpn/ca# bash -x ./easyrsa --vars="./vars" gen-crl
+ NL='
'
+ '[' -z '' ']'
+ umask 077
+ :
+ opt=--vars
+ val=./vars
+ empty_ok=
+ case "$opt" in
+ export EASYRSA_VARS_FILE=./vars
+ EASYRSA_VARS_FILE=./vars
+ '[' '!' ']'
+ '[' ./vars = --vars=./vars ']'
+ '[' -z ./vars ']'
+ shift
+ :
+ opt=gen-crl
+ val=gen-crl
+ empty_ok=
+ case "$opt" in
+ break
+ vars_setup
+ vars=
+ prog_file=./easyrsa
++ which -- ./easyrsa
+ prog_file2=./easyrsa
+ prog_file=./easyrsa
++ readlink -f ./easyrsa
+ prog_file2=/usr/share/easy-rsa/easyrsa
+ prog_file=/usr/share/easy-rsa/easyrsa
+ prog_dir=/usr/share/easy-rsa
+ prog_vars=/usr/share/easy-rsa/vars
+ pki_vars=/etc/openvpn/ca/pki/vars
+ '[' '!' -z ./vars ']'
+ '[' '!' -f ./vars ']'
+ vars=./vars
+ '[' -z '' ']'
+ '[' -n ./vars ']'
+ grep -Eq 'EASYRSA_PASSIN|EASYRSA_PASSOUT' ./vars
+ EASYRSA_CALLER=1
+ . ./vars
```

Here it finds the vars file and takes the environment variables to use to generate whatever you need to. 
I can't really make heads or tails why this happens. If it's because it's a symbolic link or because somewhere in the script it's not coded properly to realise where the easyrsa is being run from. The way this is checked seems a bit lazy.

```1666         # set up program path
1667         prog_file="$0"
1668         prog_file2="$(which -- "$prog_file" 2>/dev/null)" && prog_file="$prog_file2"
1669         prog_file2="$(readlink -f "$prog_file" 2>/dev/null)" && prog_file="$prog_file2"
1670         prog_dir="${prog_file%/*}"
1671         prog_vars="${prog_dir}/vars"
```

I'm going to see if I can spend some time tomorrow and make this better.

Cheers,

Dario Susman

**Comment by dariosusman** [comment]
I think I may have resolved it. I'm posting the fix now.
