### ISSUE TITLE
Why not use a direct "pass:" on EASYRSA_PASSIN?

### ISSUE THREAD

**Issue by arthur4ires** [OpenVPN/easy-rsa#435]
Hello, I was having trouble signing certificates automatically, even after setting EASYRSA_PASSIN.

I realized that a "pass:" was missing before the variable, as described here in the stackoverflow.
https://stackoverflow.com/questions/30426586/how-to-specify-ca-private-key-password-for-client-certificate-creation-using-ope

Is this lack of pass on purpose?

Thanks for listening!

**Comment by Deantwo** [comment]
Yes. The "pass:" is not included so that you can use the same option to specify an environment variable with "env:" or a file with "file:" as well. If "pass:" was pre-defined, it would be impossible to use those other options.

See: https://www.openssl.org/docs/manmaster/man1/openssl-passphrase-options.html

**Comment by arthur4ires** [comment]
Okay, despite the delay, thank you very much for the clarification!

**Comment by TinCanTech** [comment]
This could almost be incorporated _as-is_ into the source as `README-passwords.md`

PRs welcome..
