### ISSUE TITLE
Signed Certificate holds decoded data rather than simply PEM format certificate.

### ISSUE THREAD

**Issue by pratick5** [OpenVPN/easy-rsa#440]
I would like to appreciate the way the library is written and how it helps us.

What I have found is that in SSL certificate(CA-signed certificate) there is a lot of decoded data rather than simply a string that starts with "-----BEGIN CERTIFICATE-----" and ends with "-----END CERTIFICATE-----".
so there is any way to achieve this, if yes please let me know 

**NOTE:** I am new to this, so correct me if  I am wrong!

looking forward to hearing from you :)

**Comment by ptrdlbrg** [comment]
I noticed this too and I came here to see if it had been reported before. 

The fix for this is to edit the easyrsa script and add a `-notext` command line argument into the command which generates the certificate. On the current master branch it is this command:
https://github.com/OpenVPN/easy-rsa/blob/243bb708b02897c563631ce62633d90ae80c82ff/easyrsa3/easyrsa#L945-L946

One way to make the necessary change is to open the easyrsa script in a text editor and change
```
easyrsa_openssl ca -utf8 -in "$req_in" -out "$crt_out_tmp" \
```
to 
```
easyrsa_openssl ca -utf8 -in "$req_in" -out "$crt_out_tmp" -notext \
```

I performed that change on my local installation and all new certificates no longer have the text form of the certificate in the file.

**Comment by gajjarvini** [comment]
Hi @ptrdlbrg 

Thank you for the solution!

**Comment by TinCanTech** [comment]
What is the reason to omit this data ?

**Comment by TinCanTech** [comment]
Could this be transferred to **discussions** ?

**Comment by TinCanTech** [comment]
Could add something like:
```
./easyrsa build-client-full apple nopass notext
```

**Comment by TinCanTech** [comment]
> It may cause problems with some applications that don't expect anything but the usual certificate data. Obviously such applications _should_ ignore anything outside of the BEGIN and END markers, but we can't control what other people's code does.

Any software of such inferior quality is not considered to be worth supporting by Easy-RSA.





> I'd prefer the `-notext` just be incorporated into the script.

But nobody else would..
