### ISSUE TITLE
Drop POSIX claim

### ISSUE THREAD

**Issue by ecrist** [OpenVPN/easy-rsa#561]
I proposing dropping the claim to adhere to POSIX in favor of a looser claim to a happy-medium of BSD/GNU compatibility.

I'd even go so far as to say we will support a short list of operating systems that we can modify.

For starters:

1. *BSD (Free/Net/Open/Dragonfly)
2. Linux (GNU)
3. BusyBox
4. Darwin/macOS (aka BSD)

Thoughts?  This was kind of highlighted in #559.

**Comment by TinCanTech** [comment]
`easyrsa` has never been strictly POSIX because doing so would require dropping support for Windows. 

Eg: `cleanup()` and to a lesser extent `hide_read_pass()`

To a larger extent, _aiming for POSIX compliance_, while exercising careful non-compliance, is exactly what a good script does. That is, "Until" "They" "Fix Everything".

**Comment by TinCanTech** [comment]
`easyrsa` passes `shellcheck` definition of POSIX, with only the exception of Windows, mentioned above.

**Comment by TinCanTech** [comment]
This could be the ouzo, grappa, schnapps, brandy, gin, whiskey, bourbon, saki or ghosts projecting through my diluted and divided soul, however, I believe that `easyrsa` is **exemplar** of _good, old_ POSIX.

**Comment by TinCanTech** [comment]
Can we then conclude that `easyrsa` is POSIX and will do what-ever it can to remain so ?

**Comment by TinCanTech** [comment]
The original question here is bogus.

Adhering to POSIX is clearly a simpler task 
than providing specific OS support.

Until there is a POSIX deal-breaker,
EasyRSA is POSIX compliant.
