### ISSUE TITLE
Support for crlDistributionPoints?

### ISSUE THREAD

**Issue by ProbablyRusty** [OpenVPN/easy-rsa#71]
Is there a way to specify `crlDistributionPoints` in easyrsa?

**Comment by ecrist** [comment]
This is not, currently.

**Comment by marcoslois** [comment]
I think it's already included, if take a look at x509-types dir you can attach this info to all types on to specific ones adding required extensions:

```
authorityInfoAccess     = caIssuers;URI:http://example.com/ca.crt,OCSP;URI:http://ocsp.example.com
crlDistributionPoints   = URI:http://example.com/ca.crl
```

You can add other extensions also.

**Comment by viharm** [comment]
Yes, I was concerned about this too. However based on the comment by @marcoslois , I tried with a simple start.

I added the following line to ...`/EasyRSA/IntCA/x509-types/server`
```ini
crlDistributionPoints = URI:http://ca.domain.tld/crl.pem
```
All certificates issued since, have this CRL distribution point (obfuscated) in it.

I have however revoked a test certificate and placed the new CRL at the above CDP, but somehow both _Firefox_ and _curl_ still accept it. Not sure how to test a revoked certificate.

**Comment by viharm** [comment]
Just noticed a very good explanation in #15 here https://github.com/OpenVPN/easy-rsa/pull/15#issuecomment-30857218.

There is already built-in support for CDP. Simple uncomment this line https://github.com/OpenVPN/easy-rsa/blob/19a20046ca0110ad5435d69f481c5148726af252/easyrsa3/x509-types/COMMON#L7 and change the URL to point to your CDP.

No need to specifically add the line to the `server` configuration as this applies to all certificates issued - awesome!

Shouldn't this issue be closed?

**Comment by TinCanTech** [comment]
@jasonhe54 current `gitmaster/easyrsa` will copy those files to your PKI for use.

Try:
```
easyrsa show-ca
```
Should copy the files.

**Comment by TinCanTech** [comment]
Personally, editing `COMMON` seems like the most obvious solution.

A command line option is less reliable ..
