### ISSUE TITLE
Add update-db to verify_ca_init (or let it run on most operations otherwise)

### ISSUE THREAD

**Issue by JochenKorge** [OpenVPN/easy-rsa#920]
I struggled with the "update-db" option.
I expected this functionality to be run every time before something will be changed in the DB. 
Is there any reasoning (besides performance) why this isn´t run with verify_ca_init?

If you agree, I´ll make a pull request.
If performance is a concern, I´d suggest a "date of last check" as first line of index.txt and only run if last check is (default) >1 day.

Let me hear your thoughts

**Comment by TinCanTech** [comment]
> I´d suggest a "date of last check" as first line of index.txt

I suggest that you _learn_ what **OpenSSL** `index.txt` is for, before attempting code changes.

Anyway, you are free to submit pull-requests but be prepared for positive and/or negative feedback.

**Comment by JochenKorge** [comment]
Well, my first proposal is to run `update-db` nearly every time when `easyrsa` is used (every time `verify_ca_init` is run). I do not see any reason why you would want to work with an outdated Database. If there is one, please let me know!

If - and only if - that´s a performance concern I´d suggest "date of last check" is saved **anywhere** and **something like** 
```
if  [ $last_check + $check_interval < $date ] ; then
    update-db
fi
```
is used instead. 

`index.txt` is the wrong file I´ll happily admit

My first thought was to "piggyback" an existing file to prevent bloat in the `pki` directory - which is clearly wrong. 
A separate file is probably the only and easiest solution to prevent breaking things and maintain backward compatibility.

I didn´t want to write a PR if there are good reasons against it. The hint to use another file is fine.

**Comment by TinCanTech** [comment]
At this stage, I am not convinced that there is any reason to automate `updte-db`.

**Comment by TinCanTech** [comment]
FTR:
```
# update-db backend
update_db() {
	verify_ca_init

```
Your proposal is to _essentially_ reverse the dependency.

Instead of:
- `update_db` requiring `verify_ca_init`

You propose that:
- `verify_ca_init` invoke `update_db`

Something along that line of reasoning .... ?

**Comment by JochenKorge** [comment]
Sorry, I wasn´t clear enough why I wanted that change.

I expect easyrsa to take care of most nitty grittys of openssl. 
So I was taken by surprise when I got tons of  serial mismatches when running e.g. `show-expire`.
While investigating I realized, that `index.txt` told me, that expired certs were still valid according to the Database. 
So I think, that ´update-db´ should be run on a regular basis. There is imho no reason to have an outdated DB.
I chose `verify_ca_init` in my proposal because it´s part of most `easyrsa` commands => DB gets updated (nearly) every time the CA is used.

While writing this, I realized, that `update-db` does not fix the `serial mismatch` error. **This seems to be a bug**
The functions `expire_status` and `renew_status` do only test the SN against the corresponding cert, throwing a `serial mismatch` information when encountering the issued/renewed cert. This is pretty confusing. I´ll open another issue for this (probably tomorrow or monday)

**Comment by TinCanTech** [comment]
> While writing this, I realized, that `update-db` does not fix the `serial mismatch` error. **This seems to be a bug**

A serial mismatch is caused by renewing a certificate.

Listed in `index.txt` as follows:
```
V  ${near-date-of-expiry}  ${serial-A} ... CN/client1
V  ${future-date-of-expiry}  ${serial-B} ... CN/client1
etc
```
Serial-A is the certificate which was renewed.
Serial-B is the new certificate.
Both certificates share the same CN.

`update-db` has no effect on this.

To resolve the problems of mismatched serial numbers the old certificate (Serial-A) must be revoked. The command `revoke-renewed client1` will revoke the old certificate, with the caveat detailed below.

This will revoke the old certificate, which will also update the database.

**Caveat**: If you have a lot of renewed certificates then it is likely some of them will need to use the command `rewind-renew SERIAL-NUMBER` before the old certificate can be revoked.

This is documented [here](https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Renew-and-Revoke.md#resolving-issues-with-renew-version-1)

**Comment by TinCanTech** [comment]
With regard to bugs in status reports; there are known bugs, there are likely to be unknown bugs too.

The status reports were created to help users navigate the problems caused by the old version of `renew` V1, which is also documented in the link above.

Those problems have a resolution, which is to `rewind-renew`.

If you have used the old version of `renew` and now need to use `rewind-renew` then it will be good to open a new issue specifically for that problem.  We can work together to document your usage and provide answers to questions as they arise.

**Comment by TinCanTech** [comment]
After all this, there is one point of note:
- The current `renew` mechanism relies on the old certificate, which has been renewed to a new certificate, be **revoked**.  Allowing the old certificate to expire without being revoked means that the same CN cannot be renewed again, until the old certificate is revoked.

Requiring that old certificates, which have been renewed, be revoked, works for me. However, it may seem a little heavy handed to others.
